name: CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.NPM_JS_TOKEN_KEY }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # or your preferred version

    - name: Install dependencies
      run: npm install

    - name: Build the package
      run: npm run build # if applicable

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
